### PR TITLE
fix: change 'string' to 'String'

### PR DESCRIPTION
**Pull request by wampirchikkkk**
Change 'string' to 'String', because that class name.

### CODE REVIEW

**Comment by wampirchikkkk** [comment]
> Good catch.
> 
> Looks like there's a similar issue in `api/session.md` which has a `Promise<string>` annotation -- could you pick that up in this PR too?

**Comment by wampirchikkkk** [comment]
Oops, i clicked on wrong button.

**Comment by wampirchikkkk** [comment]
Sorry, i don't see that issue in `api/session.md`

**Comment by HashimotoYT** [comment]
If you modifying original documentation please do this in [`electron/electron`](https://github.com/electron/electron/tree/master/docs) repository in the docs folder. This repository doesn't accept PR to modifying content folder manually.

**Comment by ckerr** [comment]
Whoops, thanks for that @HashimotoYT. I was looking at all of `electron/*`'s PRs and mistakenly didn't realize this was in `electron/i18n`

**Comment by ckerr** [comment]
Follow-up in https://github.com/electron/electron/pull/18368

**Pull request closed without merging**
