### PR TITLE
feat: add temporary plaintext transformer for invalid lang tags

### PR DESCRIPTION
**Pull request by DeerMichel**
Follow-up to https://github.com/electron/i18n/pull/769 and https://github.com/electron/electron/pull/19513.

This transformer will replace `text` and `txt` language tags on code blocks with `plaintext` to ensure support of the [code highlighting remark plugin](https://github.com/highlightjs/highlight.js/blob/master/docs/css-classes-reference.rst#language-names-and-aliases) with older docs versions.

**It can be removed after support for versions which docs use invalid plaintext tags has been dropped.**

cc @HashimotoYT @zeke

### CODE REVIEW

**Comment by DeerMichel** [comment]
There's a problem in [this translated file](https://github.com/electron/i18n/blob/master/content/tr-TR/docs/api/protocol.md#protocolregisterschemesasprivilegedcustomschemes). A missing line break:
```
```html<body>
  <img src='test. png'>
</body>
```

**Comment by HashimotoYT** [comment]
Okay, this only one issue what we have, so need to await when this fix goes to master, rebase and these tests should be a pass 🦄.

**Comment by DeerMichel** [comment]
It looks like Github Actions are down again 🤔

**Comment by DeerMichel** [comment]
check, ready to merge ✅

**Comment by DeerMichel** [comment]
Again the same problem mentioned above 😆

**Pull request merged**
