### PR TITLE
feat: wordcount

### PR DESCRIPTION
**Pull request by zeke**
This PR adds a little script for counting words in `content/en-US` and aggregating some stats into a little report.

## English

Stat | Value
---- | -----
total files | 161
total words | 155583
unique words | 8034
average words per file | 966

## All Languages

Stat | Value
---- | -----
total files | 3996
total words | 3026896
unique words | 70695
average words per file | 757

cc @alebourne @bernars

### CODE REVIEW

**Comment by alebourne** [comment]
@zeke Another data point from Crowdin that you may want to add is the total number of translated words. As of now, Electron has 1,400,607
Yes! almost 1.5 million words translated since project start!!!

**Comment by zeke** [comment]
💡 Good idea, @alebourne 

I updated the code and the original comment above to show stats for English and all languages in aggregate.  **3 millions words** by this count!

>  Electron has 1,400,607

How are you finding this figure? I wonder what the difference is in this calculation.

**Comment by zeke** [comment]
Went ahead and merged this. We can iterate if needed.

**Comment by alebourne** [comment]
Hi @zeke,

Here is how I get that number: 
1. Go to the Electron Project
2. Click Settings
3. Click Reports
4. Select "year". FYI:  I selected "year"  because I know that the project has been in translation for less than 1 year, so 1 year would cover all translations up to now.
5. Select "words" from the drop-down menu on the top right side.

Here is a screenshot of what I see, of course by now the words number has slightly increased:
screen shot 2018-04-18 at 8 24 02 am

**Pull request merged**
