### PR TITLE
build: disable tests on updating for now

### PR DESCRIPTION
**Pull request by HashimotoYT**

### CODE REVIEW

**Comment by malept** [comment]
What's the context here?

**Comment by HashimotoYT** [comment]
@malept  I'm want to try do this https://github.com/electron/i18n/issues/836#issuecomment-543312663, fetch source context, release new version and try to fix CI.

**Comment by malept** [comment]
This will unblock the website from having updated docs, I take it?

**Comment by malept** [comment]
In any event, "Run tests" seems to be stuck (which is preventing me from clicking the merge button).

**Comment by HashimotoYT** [comment]
> This will unblock the website from having updated docs, I take it?

Should, if new release be created, website takes her. I'm take the broken CI after this.

> In any event, "Run tests" seems to be stuck (which is preventing me from clicking the merge button).

Need someone with write access to remove this required check. The stucked check it's broken due migration to Actions v2

**Comment by malept** [comment]
@HashimotoYT what about temporarily commenting out this as well:

https://github.com/electron/i18n/blob/cd1a863ae14a86749a6b58ac314e8ab3084754ce/.github/workflows/push.yml#L16-L19

**Comment by HashimotoYT** [comment]
@malept I'm not very want temporary comment this. The main reason for it: if new content doesn't fix the CI (linked issue above) its can be tracked faster than creating new PR when new content be fetched. For me makes sense leave this if this still be red.

**Comment by HashimotoYT** [comment]
Rethinking of previous comment: Extracted test run to own file regarding to how does releases created from master. These needed for really get release under broken tests, this file should be removed after CI be fixed.

**Comment by HashimotoYT** [comment]
Okay, let's give chance for these.

**Pull request merged**
